### ISSUE TITLE
Error while processing the app definition file

### ISSUE THREAD

**Issue by aleksic87** [Activiti/activiti-examples#12]
Hi,

I tried to import the loan-request-7-201711-EA.jar (renamed to .zip because APS requires this) but I get this error:

Error while processing the app definition file : Could not find app definition json loan-request-7-201711-EA.zip

/Jimmie

**Comment by salaboy** [comment]
@aleksic87 sorry.. we don't monitor this repo for issues.. 
Did you got it working in the end? Please create an issue in GitHub.com/activiti/activiti
