### ISSUE TITLE
Is this example working?

### ISSUE THREAD

**Issue by jian-tang** [Activiti/activiti-examples#25]
I am getting the following exception when running mvn command:

 at 96 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.activiti.dependencies:activiti-dependencies:pom:7.0.25 in central (https://repo.maven.apache.org/maven2) @ line 29, column 19
[ERROR] 'dependencies.dependency.version' for org.activiti:activiti-spring-boot-starter:jar is missing. @ line 45, column 17
 @

**Comment by jian-tang** [comment]
It worked after I added this to pom.xml
 <repository>
    <id>activiti</id>
    <name>activiti</name>
    <url>https://artifacts.alfresco.com/nexus/content/repositories/activiti/</url>
  </repository>

Update readme?

**Comment by knowings** [comment]
@jian-tang : The XML you put is escaped...

**Comment by salaboy** [comment]
@jian-tang @knowings let me update the README. I will also mention that these examples are being updated with fixed versions which are not in maven central, but in our internal nexus.
